apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    version: 1
    editable: false

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    version: 1
    editable: false
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: loki
          matcherRegex: '"transaction_id":"(txn_[^"]+)"'
          name: TransactionID
          url: '$${__value.raw}'
        - datasourceUid: loki
          matcherRegex: '"order_id":"(ord_[^"]+)"'
          name: OrderID
          url: '$${__value.raw}'
        - datasourceUid: loki
          matcherRegex: '"user_id":"(usr_[^"]+)"'
          name: UserID
          url: '$${__value.raw}'
