server:
  port: 8003

spring:
  application:
    name: order-service
  scheduling:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  config: classpath:log4j2-spring.xml
